kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    # Map ports for ArgoCD access
    extraPortMappings:
      - containerPort: 30080
        hostPort: 8090
        protocol: TCP
      - containerPort: 30443
        hostPort: 9443
        protocol: TCP
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry]
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors."gitea:3000"]
        endpoint = ["http://gitea:3000"]
      [plugins."io.containerd.grpc.v1.cri".registry.configs."gitea:3000".tls]
        insecure_skip_verify = true
    [plugins."io.containerd.grpc.v1.cri".registry]
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors]
        [plugins."io.containerd.grpc.v1.cri".registry.mirrors."registry:5000"]
          endpoint = ["http://registry:5000"]
      [plugins."io.containerd.grpc.v1.cri".registry.configs]
        [plugins."io.containerd.grpc.v1.cri".registry.configs."registry:5000".tls]
          insecure_skip_verify = true        